[project]
name = "mockgen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "deltalake==0.14",
    "faker>=37.4.0",
    "pandas>=2.3.0",
    "requests>=2.32.4",
    "streamlit>=1.46.1",
]
